### ISSUE TITLE
Iteration 1 - Checklist

### ISSUE THREAD

**Issue by andrewvallejo** [andrewvallejo/thirteen-moons#1]
The general setup to get the API working at its core & general component setup

## Checklist

- [ ] Plug in API
- [ ] Add the images to the cards
- [x] Deploy to heroku
- [ ] Make components
